### ISSUE TITLE
Question about localizeddate

### ISSUE THREAD

**Issue by ghost** [vojtasvoboda/oc-twigextensions-plugin#24]
Hello,

I have some difficulties to output the month in french using the localizeddate function.

I tried :

    localizeddate('none', 'none', null, null, 'F')

But it doesn't seems to work, it display me a number instead of the month.

What should I do to display, the month in French for example ?

Thanks

**Comment by vojtasvoboda** [comment]
Have you tried this locale code: `fr-FR` instead of `F`?

**Comment by qroft** [comment]
Unfortunately i have to re-open this again as i am having the same problem!
I am using the rainlab translation plugin.
My translations work and i can see that the locale code is set to "es" or "en" or "de" depending on the selected language.

I have set a variable called "appLanguage" that contains the locale code as mentioned above..
**The question is this**
Am i correct by saying that the code used with localizeddate is not for example "es" but "es-ES" ?

Because at the moment al i get with
{{event_start | localizeddate('none', 'none', localeCode, 'Atlantic/Canary', 'F')}}
the result is "2"

**Comment by qroft** [comment]
[SOLUTION]
I found out that i was using the incorrect "F" format tag for the month name.
You have to use the PHP codes from datetime!

http://userguide.icu-project.org/formatparse/datetime
