### ISSUE TITLE
Does not work with new version of OctoberCMS (v40

### ISSUE THREAD

**Issue by codebugs** [vojtasvoboda/oc-twigextensions-plugin#29]
Hi,

I just (edge) upgraded to OctoberCMS version 420 (LTS) and now I receive the following error message regarding Twix extensions plugin:

> Type error: Argument 1 passed to Twig_Extensions_Extension_Date::__construct() must implement interface Symfony\Component\Translation\TranslatorInterface or be null, instance of VojtaSvoboda\TwigExtensions\Classes\TimeDiffTranslator given, called in ...plugins\vojtasvoboda\twigextensions\Plugin.php on line 208

Regards,
CB

**Comment by codebugs** [comment]
Hi,

I just (edge) upgraded to OctoberCMS version 420 (LTS) and now I receive the following error message regarding Twix extensions plugin:

> Type error: Argument 1 passed to Twig_Extensions_Extension_Date::__construct() must implement interface Symfony\Component\Translation\TranslatorInterface or be null, instance of VojtaSvoboda\TwigExtensions\Classes\TimeDiffTranslator given, called in D:\OneDrive\Raben\Development\htdocs\edi\plugins\vojtasvoboda\twigextensions\Plugin.php on line 208

Regards,
CB

**Comment by Fl0Cri** [comment]
Just got exactly the same problem. I had a quick look and it seems that in build 420, the `October\Rain\Translation\Translator` class used by `VojtaSvoboda\TwigExtensions\Classes\TimeDiffTranslator` has moved from the Symfony interface `Symfony\Component\Translation\TranslatorInterface` to the Laravel one `Illuminate\Contracts\Translation\Translator` (available since Laravel 5.4).
- build 419: https://github.com/octobercms/library/blob/master/src/Translation/Translator.php#L13
- build 420: https://github.com/octobercms/library/blob/develop/src/Translation/Translator.php#L13

Currently, both interfaces looks the same:
- https://github.com/symfony/translation/blob/master/TranslatorInterface.php
- https://github.com/laravel/framework/blob/master/src/Illuminate/Contracts/Translation/Translator.php

So I did this to fix my v420 site in https://github.com/vojtasvoboda/oc-twigextensions-plugin/blob/master/classes/TimeDiffTranslator.php#L6:
```PHP
// Current
class TimeDiffTranslator extends Translator
{}

// Fixed
use Symfony\Component\Translation\TranslatorInterface;
class TimeDiffTranslator extends Translator implements TranslatorInterface
{}
```

Sorry for not making a PR, I havn't time yet to test it more deeply and see if there are side-effects. However, it fixes the fatal error and should be backward compatible.

**Comment by vojtasvoboda** [comment]
Hi guys, sorry for troubles. I have made PR and now waiting for tests: https://github.com/vojtasvoboda/oc-twigextensions-plugin/pull/30

**Comment by vojtasvoboda** [comment]
Update 1.1.0 now ready. Please update at your backend. Thanks guys again for testing.
