### ISSUE TITLE
The style "120000.00" does not exists (localizednumber)

### ISSUE THREAD

**Issue by jvanremoortere** [vojtasvoboda/oc-twigextensions-plugin#4]
When trying to use localizednumber on a decimal field as follows...

```
{{ lot.price | localizednumber('decimal') }}
```

(tried it without defining it as decimal and with)
 I get the following error:

```
The style "120000.00" does not exist. Known styles are: "decimal", "currency", "percent", "scientific", "spellout", "ordinal", "duration"
```

while...

```
$table->decimal('price', 9, 2)->nullable();
```

What am I not seeing here?

**Comment by vojtasvoboda** [comment]
Which version of PHP do you use, please? And which version of php-intl extension? Because I try it right now with last October version, on PHP 5.6.19 and php56-intl 5.6.19 also.

Try to download October update and also try update this plugin, please.

My try:

![snimek obrazovky 2016-04-21 v 10 59 27](https://cloud.githubusercontent.com/assets/374917/14703495/6659ce0e-07b0-11e6-8f69-bd5c9ecfea39.png)

![snimek obrazovky 2016-04-21 v 10 59 39](https://cloud.githubusercontent.com/assets/374917/14703498/68ff01f6-07b0-11e6-9634-5cc56182b949.png)

**Comment by jvanremoortere** [comment]
It's on my test server (wamp64)
PHP 5.6.16... But my decimal from the database returns 120000.00
Have you tried it that way?

**Comment by vojtasvoboda** [comment]
Same result:

![snimek obrazovky 2016-04-21 v 11 30 31](https://cloud.githubusercontent.com/assets/374917/14704361/87940252-07b4-11e6-8b3c-f320125d2e5e.png)

![snimek obrazovky 2016-04-21 v 11 30 37](https://cloud.githubusercontent.com/assets/374917/14704363/89b3577c-07b4-11e6-84fa-fe6c5655b346.png)

Can you please check your versions with mine below?

![snimek obrazovky 2016-04-21 v 11 31 41](https://cloud.githubusercontent.com/assets/374917/14704395/ab15f262-07b4-11e6-9b3b-7f4ab82e29ee.png)

**Comment by jvanremoortere** [comment]
Updated! Works now... Had 1.0.5

**Comment by vojtasvoboda** [comment]
Cool! I'm glad it works.
