### ISSUE TITLE
It doesn't translate

### ISSUE THREAD

**Issue by hambern** [vojtasvoboda/oc-twigextensions-plugin#40]
Hello! First of all: a fantastic plugin and a very good job. Now to the bad...

The app.locale is correctly set to 'sv', confirmed by {{ config('app.locale') }}. But when I try this:

```
{{ event.published_at|strftime('%a %d %h, %H:%M') }}
```

... but the output is in english: Thu 18 Jan, 19:42

I've also tried other languages with the same result. It doesn't seem to work. Any tips?

**Comment by vojtasvoboda** [comment]
Hello Hambern,

`config('app.locale')` does not confirm system locale setting, it just prints a value from the config file. When I installed fresh OctoberCMS demo and created homepage like this:

```
title = "Demonstration"
url = "/"
layout = "default"
is_hidden = 0
==
<?php
function onStart() {
    setlocale(LC_ALL, 'sv_SE');
}
?>
==
<div class="container">
    <p>
        {{ '2018-01-20 11:53:53' | strftime('%a %d %h, %H:%M') }}
    </p>
</div>
```

It has printed: `Lör 20 Jan, 11:53`. So it looks like a problem with setting locale on the OctoberCMS level because my plugin only uses `strftime` internal PHP function and does not set any locale at all.

**Comment by hambern** [comment]
Ah, sorry. I just had to restart the php-service. My bad. You're awesome!
